-- Basic Profile for Profile Manager
-- v0.9.2+

services.add(

	-- service name
	"basicprofile",
	
	-- description
	"Installs a basic profile",
	
	-- category
	"profile",
	
	-- execute
	function(cn)
	end,
	
	-- activate
	function(cn)
		services.write(cn, "basicprofile", [=[
log "SERVICES" "info" "Installing Basic Profile"
list_insert "_PROFILES" "BASIC"
"_PROFILE_BASIC_KEYS" = [_KEY_FILEEDITOR_OPEN _KEY_LOGIN_OPEN _KEY_PLUGINMANAGER_OPEN _KEY_MUSICPLAYER_OPEN _KEY_MUSICPLAYER_NEXT _KEY_MUSICPLAYER_PREV _KEY_MUSICPLAYER_STOP _KEY_WHEELZOOM_DOUBLE _KEY_WHEELZOOM_TRIPPLE _KEY_WHEELZOOM_IN _KEY_WHEELZOOM_OUT _KEY_AUTOSPEC_FORWARD _KEY_AUTOSPEC_BACKWARD _KEY_AUTOSPEC_LEFT _KEY_AUTOSPEC_RIGHT _KEY_SCREENSHOOTER_OPEN]
"_PROFILE_BASIC_KEY_AUTOSPEC_BACKWARD" = [S]
"_PROFILE_BASIC_KEY_AUTOSPEC_FORWARD" = [W]
"_PROFILE_BASIC_KEY_AUTOSPEC_LEFT" = [A]
"_PROFILE_BASIC_KEY_AUTOSPEC_RIGHT" = [D]
"_PROFILE_BASIC_KEY_FILEEDITOR_OPEN" = [F6]
"_PROFILE_BASIC_KEY_LOGIN_OPEN" = [F2 MENU]
"_PROFILE_BASIC_KEY_MUSICPLAYER_NEXT" = [MINUS]
"_PROFILE_BASIC_KEY_MUSICPLAYER_OPEN" = [F9]
"_PROFILE_BASIC_KEY_MUSICPLAYER_PREV" = [PERIOD]
"_PROFILE_BASIC_KEY_MUSICPLAYER_STOP" = [BACKSPACE]
"_PROFILE_BASIC_KEY_PLUGINMANAGER_OPEN" = [F7]
"_PROFILE_BASIC_KEY_SCREENSHOOTER_OPEN" = [F12]
"_PROFILE_BASIC_KEY_WHEELZOOM_DOUBLE" = [G]
"_PROFILE_BASIC_KEY_WHEELZOOM_IN" = [MOUSE4]
"_PROFILE_BASIC_KEY_WHEELZOOM_OUT" = [MOUSE5]
"_PROFILE_BASIC_OPTIONS" = [_OPTION_PLUGINS_ACTIVE _OPTION_EHS_MAXFPS _OPTION_EHS_THIRDPERSON _OPTION_EHS_SHOWPJ _OPTION_EHS_SHOWCLIENTNUM _OPTION_EHS_NVIDIATEXGENBUG _OPTION_EHS_GAMESPEED _OPTION_PATHFINDER_RUNNING _OPTION_GAMEPLAY_PLAYERSLOTS _OPTION_CHANGEMAP_IMMEDIATELY _OPTION_CHANGEMAP_NEXTMAPCHOOSEN _OPTION_SCREENSHOOTER_FIXEDPATH _OPTION_SCREENSHOOTER_FOLDER _OPTION_SCREENSHOOTER_FILENAME _OPTION_SCREENSHOOTER_FILECOUNT _OPTION_SCREENSHOOTER_HUD _OPTION_SCREENSHOOTER_GUN _OPTION_SCREENSHOOTER_STATS _OPTION_SCREENSHOOTER_EFFECT_BLOOM _OPTION_SCREENSHOOTER_BLOOM _OPTION_SCREENSHOOTER_BLOOM_VALUE _OPTION_SCREENSHOOTER_EFFECT_AURA _OPTION_SCREENSHOOTER_EFFECT_NEGATIVE _OPTION_SCREENSHOOTER_EFFECT_GBR _OPTION_SCREENSHOOTER_EFFECT_BW _OPTION_SCREENSHOOTER_EFFECT_BLUR3 _OPTION_SCREENSHOOTER_EFFECT_BLUR5 _OPTION_LOGIN_NAME _OPTION_AUTOSPEC_IS_AFK _OPTION_AUTOSPEC_TAKT _OPTION_AUTOSPEC_SECS _OPTION_AUTOSPEC_WARNING_SECS _OPTION_MUSICPLAYER_FOLDER _OPTION_MUSICPLAYER_PLAY _OPTION_MUSICPLAYER_NOWPLAYING _OPTION_MUSICPLAYER_NEXTSONGINROTATION _OPTION_MOVIERECORDER_RECORD _OPTION_MOVIERECORDER_FIXEDPATH _OPTION_MOVIERECORDER_FOLDER _OPTION_MOVIERECORDER_FILENAME _OPTION_MOVIERECORDER_FILECOUNT _OPTION_MOVIERECORDER_RESOLUTION_WxH _OPTION_MOVIERECORDER_RESOLUTION_H _OPTION_MOVIERECORDER_SOUND _OPTION_MOVIERECORDER_HUD _OPTION_MOVIERECORDER_EFFECT_BLOOM _OPTION_MOVIERECORDER_BLOOM _OPTION_MOVIERECORDER_BLOOM_VALUE _OPTION_MOVIERECORDER_EFFECT_AURA _OPTION_MOVIERECORDER_EFFECT_NEGATIVE _OPTION_MOVIERECORDER_EFFECT_GBR _OPTION_MOVIERECORDER_EFFECT_BW _OPTION_MOVIERECORDER_EFFECT_BLUR3 _OPTION_MOVIERECORDER_EFFECT_BLUR5 _OPTION_HIFRIENDS_GREETING _OPTION_HIFRIENDS_FRIENDS _OPTION_WHEELZOOM_NORM _OPTION_WHEELZOOM_MAX _OPTION_WHEELZOOM_MID _OPTION_WHEELZOOM_MIN _OPTION_WHEELZOOM_SPEED _OPTION_WHEELZOOM_MAX_SENS _OPTION_WHEELZOOM_MID_SENS _OPTION_WHEELZOOM_MIN_SENS _OPTION_RANDOMSAY_WORDS_NEGATIVE _OPTION_RANDOMSAY_WORDS_POSITIVE _OPTION_FILEEDITOR_FILENAME _OPTION_FILEEDITOR_FOLDER]
"_PROFILE_BASIC_OPTION_PLUGINS_ACTIVE" = [germankeymapextension fileeditor login pluginmanager servermanager aboutyou gameplay playercontrol speccontrol changemap nlgui keyeditor musicplayer hifriends altmainmenu noobloungeservers wheelzoom screenshooter]
"_PROFILE_BASIC_OPTION_AUTOSPEC_IS_AFK" = [0]
"_PROFILE_BASIC_OPTION_AUTOSPEC_SECS" = [180]
"_PROFILE_BASIC_OPTION_AUTOSPEC_TAKT" = [1000]
"_PROFILE_BASIC_OPTION_AUTOSPEC_WARNING_SECS" = [15]
"_PROFILE_BASIC_OPTION_CHANGEMAP_IMMEDIATELY" = [0]
"_PROFILE_BASIC_OPTION_EHS_GAMESPEED" = [100]
"_PROFILE_BASIC_OPTION_EHS_MAXFPS" = [200]
"_PROFILE_BASIC_OPTION_EHS_NVIDIATEXGENBUG" = [0]
"_PROFILE_BASIC_OPTION_EHS_SHOWCLIENTNUM" = [0]
"_PROFILE_BASIC_OPTION_EHS_SHOWPJ" = [0]
"_PROFILE_BASIC_OPTION_EHS_THIRDPERSON" = [0]
"_PROFILE_BASIC_OPTION_FILEEDITOR_FILENAME" = [autoexec.cfg]
"_PROFILE_BASIC_OPTION_FILEEDITOR_FOLDER" = [packages/nooblounge/plugins]
"_PROFILE_BASIC_OPTION_GAMEPLAY_PLAYERSLOTS" = [24]
"_PROFILE_BASIC_OPTION_HIFRIENDS_FRIENDS" = [Hankus Braten Der-W angst NuckChorris TOMYC [GE]Braten Nick foo MurderMoloch Dery DaveX]
"_PROFILE_BASIC_OPTION_HIFRIENDS_GREETING" = [Hi]
"_PROFILE_BASIC_OPTION_LOGIN_NAME" = [YOURNAME]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_BLOOM" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_BLOOM_VALUE" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_AURA" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BLOOM" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BLUR3" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BLUR5" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BW" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_GBR" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_NEGATIVE" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FILECOUNT" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FILENAME" = [movie]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FIXEDPATH" = [packages/nooblounge]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FOLDER" = [movies]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_HUD" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_RECORD" = [0]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_RESOLUTION_H" = [480]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_RESOLUTION_WxH" = [302]
"_PROFILE_BASIC_OPTION_MOVIERECORDER_SOUND" = [1]
"_PROFILE_BASIC_OPTION_MUSICPLAYER_FOLDER" = [packages/nooblounge/music/talco]
"_PROFILE_BASIC_OPTION_MUSICPLAYER_PLAY" = [0]
"_PROFILE_BASIC_OPTION_PATHFINDER_RUNNING" = [0]
"_PROFILE_BASIC_OPTION_RANDOMSAY_WORDS_NEGATIVE" = [ahhh grrr mist shit noooooooo grmpf fail]
"_PROFILE_BASIC_OPTION_RANDOMSAY_WORDS_POSITIVE" = [yeah yippie]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_BLOOM" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_BLOOM_VALUE" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_AURA" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BLOOM" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BLUR3" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BLUR5" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BW" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_GBR" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_NEGATIVE" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FILECOUNT" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FILENAME" = [screenshoot]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FIXEDPATH" = [packages/nooblounge]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FOLDER" = [screenshoots]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_GUN" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_HUD" = [0]
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_STATS" = [0]
"_PROFILE_BASIC_OPTION_WHEELZOOM_MAX" = [112]
"_PROFILE_BASIC_OPTION_WHEELZOOM_MAX_SENS" = [7]
"_PROFILE_BASIC_OPTION_WHEELZOOM_MID" = [60]
"_PROFILE_BASIC_OPTION_WHEELZOOM_MID_SENS" = [3]
"_PROFILE_BASIC_OPTION_WHEELZOOM_MIN" = [15]
"_PROFILE_BASIC_OPTION_WHEELZOOM_MIN_SENS" = [1]
"_PROFILE_BASIC_OPTION_WHEELZOOM_NORM" = [100]
"_PROFILE_BASIC_OPTION_WHEELZOOM_SPEED" = [5]
]=])
	end,
	
	-- deactivate
	function(cn)
		services.write(cn, "basicprofile", [=[
log "SERVICES" "info" "Uninstalling basic profile"
list_remove "_PROFILES" "BASIC"
"_PROFILE_BASIC_KEYS" = ""
"_PROFILE_BASIC_KEY_AUTOSPEC_BACKWARD" = ""
"_PROFILE_BASIC_KEY_AUTOSPEC_FORWARD" = ""
"_PROFILE_BASIC_KEY_AUTOSPEC_LEFT" = ""
"_PROFILE_BASIC_KEY_AUTOSPEC_RIGHT" = ""
"_PROFILE_BASIC_KEY_FILEEDITOR_OPEN" = ""
"_PROFILE_BASIC_KEY_LOGIN_OPEN" = ""
"_PROFILE_BASIC_KEY_MUSICPLAYER_NEXT" = ""
"_PROFILE_BASIC_KEY_MUSICPLAYER_OPEN" = ""
"_PROFILE_BASIC_KEY_MUSICPLAYER_PREV" = ""
"_PROFILE_BASIC_KEY_MUSICPLAYER_STOP" = ""
"_PROFILE_BASIC_KEY_PLUGINMANAGER_OPEN" = ""
"_PROFILE_BASIC_KEY_SCREENSHOOTER_OPEN" = ""
"_PROFILE_BASIC_KEY_WHEELZOOM_DOUBLE" = ""
"_PROFILE_BASIC_KEY_WHEELZOOM_IN" = ""
"_PROFILE_BASIC_KEY_WHEELZOOM_OUT" = ""
"_PROFILE_BASIC_OPTIONS" = ""
"_PROFILE_BASIC_OPTION_PLUGINS_ACTIVE" = ""
"_PROFILE_BASIC_OPTION_AUTOSPEC_IS_AFK" = ""
"_PROFILE_BASIC_OPTION_AUTOSPEC_SECS" = ""
"_PROFILE_BASIC_OPTION_AUTOSPEC_TAKT" = ""
"_PROFILE_BASIC_OPTION_AUTOSPEC_WARNING_SECS" = ""
"_PROFILE_BASIC_OPTION_CHANGEMAP_IMMEDIATELY" = ""
"_PROFILE_BASIC_OPTION_EHS_GAMESPEED" = ""
"_PROFILE_BASIC_OPTION_EHS_MAXFPS" = ""
"_PROFILE_BASIC_OPTION_EHS_NVIDIATEXGENBUG" = ""
"_PROFILE_BASIC_OPTION_EHS_SHOWCLIENTNUM" = ""
"_PROFILE_BASIC_OPTION_EHS_SHOWPJ" = ""
"_PROFILE_BASIC_OPTION_EHS_THIRDPERSON" = ""
"_PROFILE_BASIC_OPTION_FILEEDITOR_FILENAME" = ""
"_PROFILE_BASIC_OPTION_FILEEDITOR_FOLDER" = ""
"_PROFILE_BASIC_OPTION_GAMEPLAY_PLAYERSLOTS" = ""
"_PROFILE_BASIC_OPTION_HIFRIENDS_FRIENDS" = ""
"_PROFILE_BASIC_OPTION_HIFRIENDS_GREETING" = ""
"_PROFILE_BASIC_OPTION_LOGIN_NAME" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_BLOOM" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_BLOOM_VALUE" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_AURA" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BLOOM" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BLUR3" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BLUR5" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_BW" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_GBR" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_EFFECT_NEGATIVE" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FILECOUNT" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FILENAME" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FIXEDPATH" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_FOLDER" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_HUD" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_RECORD" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_RESOLUTION_H" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_RESOLUTION_WxH" = ""
"_PROFILE_BASIC_OPTION_MOVIERECORDER_SOUND" = ""
"_PROFILE_BASIC_OPTION_MUSICPLAYER_FOLDER" = ""
"_PROFILE_BASIC_OPTION_MUSICPLAYER_PLAY" = ""
"_PROFILE_BASIC_OPTION_PATHFINDER_RUNNING" = ""
"_PROFILE_BASIC_OPTION_RANDOMSAY_WORDS_NEGATIVE" = ""
"_PROFILE_BASIC_OPTION_RANDOMSAY_WORDS_POSITIVE" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_BLOOM" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_BLOOM_VALUE" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_AURA" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BLOOM" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BLUR3" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BLUR5" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_BW" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_GBR" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_EFFECT_NEGATIVE" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FILECOUNT" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FILENAME" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FIXEDPATH" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_FOLDER" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_GUN" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_HUD" = ""
"_PROFILE_BASIC_OPTION_SCREENSHOOTER_STATS" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_MAX" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_MAX_SENS" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_MID" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_MID_SENS" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_MIN" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_MIN_SENS" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_NORM" = ""
"_PROFILE_BASIC_OPTION_WHEELZOOM_SPEED" = ""
]=])
	end
)

