-- Array of game mode names, used by the map rotation module
gamemodes = {
    [ 1] = "ffa",
    [ 2] = "coop edit",
    [ 3] = "teamplay",
    [ 4] = "instagib",
    [ 5] = "instagib team",
    [ 6] = "efficiency",
    [ 7] = "efficiency team",
    [ 8] = "tactics",
    [ 9] = "tactics team",
    [10] = "capture",
    [11] = "regen capture",
    [12] = "ctf",
    [13] = "insta ctf",
    [14] = "protect",
    [15] = "insta protect",
    [16] = "hold",
    [17] = "insta hold",
    [18] = "efficiency ctf",
    [19] = "efficiency protect",
    [20] = "efficiency hold"
}

local mode_aliases = {
	["ffa"]			= "ffa",
	["lobby"]		= "ffa",
        ["coopedit"]		= "coop edit",
        ["coop"]		= "coop edit",
	["teamplay"]		= "teamplay",
	["tplay"]		= "teamplay",
	["instagib"]		= "instagib",
        ["insta"]		= "instagib",
	["instagib team"]	= "instagib team",
        ["instateam"]		= "instagib team",
        ["iteam"]		= "instagib team",
        ["efficiency"]		= "efficiency",
        ["effic"]		= "efficiency",
	["efficiency team"]	= "efficiency team",
        ["efficteam"]		= "efficiency team",
        ["eteam"]		= "efficiency team",
        ["tactics"]		= "tactics",
        ["tac"]			= "tactics",
	["tactics team"]	= "tactics team",
        ["tacteam"]		= "tactics team",
        ["tteam"]		= "tactics team",
	["capture"]		= "capture",
        ["cap"]			= "capture",
        ["regen capture"]	= "regen capture",
        ["regencapture"]	= "regen capture",
        ["regencap"]		= "regen capture",
        ["regen"]		= "regen capture",
        ["ctf"]			= "ctf",
        ["insta ctf"]		= "insta ctf",
        ["instactf"]		= "insta ctf",
        ["ictf"]		= "insta ctf",
	["protect"]		= "protect",
        ["insta protect"]	= "insta protect",
        ["instaprotect"]	= "insta protect",
        ["iprotect"]		= "insta protect",
	["hold"]		= "hold",
	["insta hold"]		= "insta hold",
	["instahold"]		= "insta hold",
	["ihold"]		= "insta hold",
	["efficiency ctf"]	= "efficiency ctf",
	["efficiencyctf"]	= "efficiency ctf",
	["efficctf"]		= "efficiency ctf",
	["ectf"]		= "efficiency ctf",
	["efficiency protect"]	= "efficiency protect",
	["efficiencyprotect"]	= "efficiency protect",
	["efficprotect"]	= "efficiency protect",
	["eprotect"]		= "efficiency protect",
    	["efficiency hold"]	= "efficiency hold",
    	["efficiencyhold"]	= "efficiency hold",
	["effichold"]		= "efficiency hold",
	["ehold"]		= "efficiency hold"
}
    
function server.parse_mode(mode)
	if mode_aliases[mode] then return mode_aliases[mode] else return "ffa" end
end
