module("alpha.logging.events", package.seeall)

server.event_handler("failedconnect", function(...) alpha.log_event("ss", "failedconnect", ...) end)
server.event_handler("connect", function(...) alpha.log_event("p", "connect", ...) end)
server.event_handler("disconnect", function(...) alpha.log_event("ps", "disconnect", ...) end)
server.event_handler("kick", function(...) alpha.log_event("piss", "kick", ...) end)
server.event_handler("rename", function(...) alpha.log_event("pss", "rename", ...) end)
server.event_handler("reteam", function(...) alpha.log_event("pss", "reteam", ...) end)
server.event_handler("text", function(...) alpha.log_event("ps", "text", ...) end)
server.event_handler("sayteam", function(...) alpha.log_event("ps", "sayteam", ...) end)
server.event_handler("mapvote", function(...) alpha.log_event("pss", "mapvote", ...) end)
server.event_handler("mapchange", function(...) alpha.log_event("ss", "mapchange", ...) end)
server.event_handler("mastermode", function(...) alpha.log_event("pss", "mastermode", ...) end)
server.event_handler("privilege", function(...) alpha.log_event("pss", "privilege", ...) end)
server.event_handler("spectator", function(...) alpha.log_event("pi", "spectator", ...) end)
server.event_handler("gamepaused", function(...) alpha.log_event("", "gamepaused", ...) end)
server.event_handler("gameresumed", function(...) alpha.log_event("", "gameresumed", ...) end)
server.event_handler("addbot", function(...) alpha.log_event("psp", "addbot", ...) end)
server.event_handler("delbot", function(...) alpha.log_event("p", "delbot", ...) end)
server.event_handler("beginrecord", function(...) alpha.log_event("is", "beginrecord", ...) end)
server.event_handler("endrecord", function(...) alpha.log_event("ii", "endrecord", ...) end)
server.event_handler("mapcrcfail", function(...) alpha.log_event("p", "mapcrcfail", ...) end)
server.event_handler("shutdown", function(...) alpha.log_event("i", "shutdown", ...) end)
